### ISSUE TITLE
[INVALID] What configuration do I need for an 'unlimited'-size value store?

### ISSUE THREAD

**Issue by 0joshuaolson1** [gholt/store#13]
The code listed after the error can't insert 100 million values.

Error:
```
{"level":"warn","ts":1530565796.5813503,"caller":"store/valuestore_GEN_.go:1023","msg":"error performing ReadTOCEntriesBatched","name":"recovery","filename":"1530564605975005298.valuetoc","error":"no terminator found"}
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gholt/store.valueReadTOCEntriesBatched(0x7696a0, 0xc420094018, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42006e300, ...)
        /home/[REDACTED]/go/src/github.com/gholt/store/valuestorefile_GEN_.go:382 +0x1181
github.com/gholt/store.(*defaultValueStore).compactFile(0xc420156000, 0xc42009c300, 0x1c, 0xc400000007, 0xc42006e300, 0x7241b7, 0x8)
        /home/[REDACTED]/go/src/github.com/gholt/store/valuecompaction_GEN_.go:411 +0x4ef
github.com/gholt/store.(*defaultValueStore).recovery(0xc420156000, 0x7378d8, 0xc420156000)
        /home/[REDACTED]/go/src/github.com/gholt/store/valuestore_GEN_.go:1047 +0x2239
github.com/gholt/store.(*defaultValueStore).Startup(0xc420156000, 0x0, 0x0, 0xc42006e120, 0xc420137cd8)
        /home/[REDACTED]/go/src/github.com/gholt/store/valuestore_GEN_.go:306 +0xace
main.main()
        /home/[REDACTED]/test.go:14 +0xcb
exit status 2
```
Code:
```
package main
import (
  DB "github.com/gholt/store"
  "fmt"
  "time"
)
func main(){
  db, _ := DB.NewValueStore(&DB.ValueStoreConfig{
    DiskFreeDisableThreshold: 1,
    DiskUsageDisableThreshold: -1,
    MemFreeDisableThreshold: 1,
    MemUsageDisableThreshold: -1
  })
  db.Startup(nil)
  t := time.Now()
  for i := uint64(0); i < uint64(100000000); i++ {
    db.Write(nil, i, i, 256, nil)
    _, _, e := db.Lookup(nil, i, i)
    if DB.IsNotFound(e){
      fmt.Println(i)
      return
    }
  }
  fmt.Println(time.Now().Sub(t))
}
```
Thanks again!

**Comment by 0joshuaolson1** [comment]
Nevermind. I think this happened when reopening the database or something.
